### ISSUE TITLE
Bug in convert_whole_word_to_feature

### ISSUE THREAD

**Issue by TheoSeo93** [qiang2100/BERT-LS#2]
```
  ind = 0
    for pos in  mask_position:
        true_word = true_word + tokens[pos]
        if(ind ==0):
            tokens[pos] = '[MASK]'
        else:
            del tokens[pos]
            del input_type_ids[pos]
        ind = ind + 1

```
This line at `convert_whole_word_to_feature` is problematic because positions of tokens changes after using `del` . Instead of deleting forward, I would consider deleting backward in order to avoid this problem like this.  I confirmed this is an error with tokenized sentence as following, 
['His', 'stories', 'g', '##lit', '##tered', 'with', 'color', ';']

  ```
  count = 0
        mask_position_length = len(mask_position)
        while count in range(mask_position_length):
            index = mask_position_length - 1 - count
            pos = mask_position[index]
            if index == 0:
                tokens[pos] = '[MASK]'
            else:
                del tokens[pos]
                del input_type_ids[pos]
            count +=1
```

Cheers!

**Comment by qiang2100** [comment]
I don't think this is a bug.  For this example "['His', 'stories', 'g', '##lit', '##tered', 'with', 'color', ';']", with mask_position=[2,3,4], I replaced the word "glittered" into "[MASK]".

**Comment by TheoSeo93** [comment]
No, after that loop goes with `del`
Here is the result of the tokens
`mask_position = [2,3,4]
tokens = ['His', 'stories', 'g', '##lit', '##tered', 'with', 'color', ';']


ind = 0
for pos in mask_position:
    if (ind == 0):
        tokens[pos] = '[MASK]'
    else:
        del tokens[pos]
    ind = ind + 1

print(tokens)
`

['His', 'stories', '[MASK]', '##tered', 'color', ';']
I don't think this is what you want to get.
