### ISSUE TITLE
Issue tested

### ISSUE THREAD

**Issue by TheoSeo93** [qiang2100/BERT-LS#4]
Thanks for your reply!  Sorry I should have described what the problem was in detail.
Here is the result of running your code.

```
mask_position = [2,3,4]
tokens = ['His', 'stories', 'g', '##lit', '##tered', 'with', 'color', ';']

ind = 0
for pos in mask_position:
    if (ind == 0):
        tokens[pos] = '[MASK]'
    else:
        del tokens[pos]
    ind = ind + 1

print(tokens)
```

`['His', 'stories', '[MASK]', '##tered', 'color', ';']`
I don't think this is what you wanted to get, isn't it? 
I thought the tokens should be like this after running

mask_position = [2,3,4]
tokens = ['His', 'stories', 'g', '##lit', '##tered', 'with', 'color', ';']

```
count = 0
mask_position_length = len(mask_position)
while count in range(mask_position_length):
    index = mask_position_length - 1 - count
    pos = mask_position[index]
    if index == 0:
        tokens[pos] = '[MASK]'
    else:
        del tokens[pos]
    count += 1
print(tokens)
```
`['His', 'stories', '[MASK]', 'with', 'color', ';']`

Thank you !

_Originally posted by @TheoSeo93 in https://github.com/qiang2100/BERT-LS/issues/2#issuecomment-520278636_

**Comment by qiang2100** [comment]
Yes, you're right
