### ISSUE TITLE
mask words not in list ?

### ISSUE THREAD

**Issue by WaNePr** [qiang2100/BERT-LS#6]
The following error occurs when runnning with dataset: lex_mturk.txt. 
Traceback (most recent call last):
  File "LS_Bert.py", line 953, in <module>
    main()
  File "LS_Bert.py", line 867, in main
    mask_index = words.index(mask_words[i])
ValueError: 'companies' is not in list

**Comment by qiang2100** [comment]
which dataset is adopted by you?

**Comment by WaNePr** [comment]
> which dataset is adopted by you?

The lex.mturk.txt as shown in the error info.

**Comment by qiang2100** [comment]
please input "lex.mturk.txt" file using command, not "lex_mturk.txt" file. Please see the code in line 840 of LS_Bert.py. 

        if fileName=='lex.mturk':
            eval_examples, mask_words, mask_labels = read_eval_dataset(args.eval_dir)
        else:
            eval_examples, mask_words, mask_labels = read_eval_index_dataset(args.eval_dir)
